### ISSUE TITLE
continous sweep runs forever - Button STOP doesn't work

### ISSUE THREAD

**Issue by DhyanRiktam** [NanoVNA-Saver/nanovna-saver#773]
**Describe the bug**
There is no opportunity to stop "continous sweep".
Tested with hardware SAA-2N and VNA-F

**To Reproduce**
1. Click on [connect to device]
2. Goto 'sweep settings' and click [continous sweep]
3. Click on [sweep]
     ...... sweep starts & application responds (can change marker etc.) ......

4. Click on [stop]
    --> nothing happend!   Sweep runs & application is  operable
    I have to kill the app

**Expected behavior**
Click on [stop] should stop sweeping

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21, windows10
 - Python version: ?
 - NanoVNA-Saver version: 0.6.8

**Additional context**
NanoVNA-Saver version 0.6.5 works fine - continous sweep can stop

**Comment by salawalas** [comment]
It's impossible to stop continuous sweeping by pressing stop button. I confirming. 
This bug is present since version 0.6.6 , I suppose.

**Desktop** (please complete the following information):

OS'es: Linux Ubuntu 24.04, Linux Debian 12, Windows 10 and 11
Python version: 3.11, 3.12.5 x64 (Windows)
NanoVNA-Saver version: 0.6.6 and later versions.
Additional context
NanoVNA-Saver version 0.6.5 works fine.
**Device**
Nano VNA-H4,  firmware 1.2.42 [DiSlord]

**Comment by zarath** [comment]
Should be fixed in latest commit.

Thank you for reporting.

**Comment by salawalas** [comment]
Hi Zarath.
Unfortunately, latest commit doesn't fix it. I can't  stop continuous sweep still, as previous.
You should to consider to open the #777 ,  program saving display setup , but not reading it at start up.
Best regards. Marcin.

![Image](https://github.com/user-attachments/assets/e13657f7-9ebb-49e9-9ef3-8bb0b573d433)

**Comment by redrathnure** [comment]
Fix in progress,... @salawalas I just curious which UI theme are you use? Is it real Windows 10?

**Comment by salawalas** [comment]
> Fix in progress,... [@salawalas](https://github.com/salawalas) I just curious which UI theme are you use? Is it real Windows 10?

Hi @redrathnure. Actually, this screenshot coming from a Windows 11, 23H2. 
Best regards. Marcin.

**Comment by salawalas** [comment]
Hi pals, @zarath&@redrathnure ! Now works like charm :). Thanks!

**Comment by DhyanRiktam** [comment]
Just started V0.7 in Linux Mint. Continous sweep works fine. Thanks.
